# Generated by Django 4.0.5 on 2022-08-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('idcourse', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=80)),
                ('hour', models.CharField(max_length=80)),
                ('credits', models.CharField(max_length=1)),
                ('state', models.CharField(max_length=20)),
            ],
        ),
    ]
