# Generated by Django 4.0.5 on 2022-08-01 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcareer', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=20)),
                ('shortname', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='Logos')),
                ('state', models.CharField(max_length=6)),
            ],
        ),
    ]
